CREATE TABLE IF NOT EXISTS CLIENT(
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,
    COORDENADAX VARCHAR(255) NOT NULL,
    COORDENADAY VARCHAR(255) NOT NULL,
)